### ISSUE TITLE
You may want to try

### ISSUE THREAD

**Issue by tunnckoCore** [doowb/error-base#1]
That's cool, but you may also want to try https://github.com/tunnckoCore/kind-error. 
More assertion-oriented, but not limited to it. If you pass `actual` and `expected` will construct the `message` automatically.
If you don't pass `actual/expected` it won't do anything magical and special. Just will merge passed options to Error props. If you pass `showStack: true` you'll get `err.stack` property, otherwise - no.

``` js
var err = new KindError('foo msg', {foo: 'bar'})
//=> err.message: 'foo msg'
// err.foo: 'bar'
```

**Comment by doowb** [comment]
This is for creating new Error sub-classes. There are a lot of other libraries out there that do this in different ways. I did this to test out a minimal implementation. This could be a library that your `kind-error` library could use to create a new `KindError` class. This one would need to be updated to handle options and check the `stack` option like you're doing.

``` js
var KindError = errorBase('KindError', function (message, options) {
  // your kind-error code here
});
```

Then create the instance of `KindError`

``` js
var err = new KindError('foo msg', {foo: 'bar'})
//=> err.message: 'foo msg'
// err.foo: 'bar'
```
